export const data = [
  "On the 22nd December 2022, the Scottish Parliament - after years of scrutiny, review and debate - overwhelmingly passed its Gender Recognition Reform Bill. This followed six years of work, including two public consultations and extensive evidence gathering. The Bill will make the process of obtaining a gender recognition certificate less invasive, medicalised and dehumanising for trans people – changes that were also overwhelmingly supported in the UK Government’s own public consultation on Gender Recognition Act reform. This Bill will align Scotland with nations worldwide, such as Canada, Australia, New Zealand and Ireland, that treat trans and non-binary people with dignity and respect - countries that value trans people and their contribution to business and society.",
  " The Scottish Bill does not affect the UK's Equality Act 2010, and it doesn't affect or reduce women's rights. Instead, it will make obtaining a gender recognition certificate less invasive, medicalised and dehumanising for trans people. It will allow trans people to live with freedom and control over their lives, enabling them to marry, live and be recognised in death as themselves."
  , " The UK Government has now blocked the Scottish Parliament's mandate to implement this Bill. It is also in the process of ending reciprocal recognition of Gender Recognition Certificates (GRCs) from all countries that support trans people changing their legal gender using self- determination after the UK has accepted them for years.", " In recent years the Government has consistently failed to support transgender and non-binary people. It has allowed those groups whose agenda is to roll back existing rights for trans people free reign in debates and policy direction.", " The Women and Equalities Select Committee have criticised the Government for fostering, through inaction and a lack of clear support for the transgender community, a climate of division and hatred. The UK has been severely criticised by international human rights organisations, including the ERC, for its anti-trans direction, with trans and non-binary hate crimes rising by 332% in the last five years. In the last few weeks, the international NGO Human Rights Watch (HRW) warned that the UK could soon make the list of countries that abuse rather than protect human rights with its \"outright assault\" on the rights of its citizens."
  , " Some of the biggest and most respected global corporates value diversity and understand the well-proven benefits of embedding inclusion in the heart of business. These benefits include more effective decision-making, increased innovation, stronger teams, better staff retention and greater talent attraction - which all lead to more profitable organisations. They know and understand the value trans and non-binary people bring to their organisations.",
   " The UK Government is creating a situation where trans and non-binary people could have their gender recognised in Scotland or another region but not in the UK, affecting their travel and flexibility work, detrimentally affecting their careers and lives. Its position does not reflect current business and what modern organisations need to thrive in an ever more challenging economic landscape. It does not reflect modern British society and harms the UK's reputation abroad.",
   " We urge all organisations to join us in asking the Prime Minister and the Government to change its direction on trans and non-binary people – to be inclusive, to support diversity, to support trans and non-binary people and their place in our society.",
   " We urge the Prime Minister and the Government to stop this constant assault on trans and non-binary people and their rights. We are, as always, here to help all organisations that wish to take positive action to improve the situation for trans and non-binary people in the UK and beyond. We're here to work with them to make positive change as soon as possible.",
   " We hope - after many years of trying - the UK Government soon understands the need to work with our member organisations and us to achieve a positive outlook for trans and non-binary people too."]

export const email = "Let's show support and raise our voices! Write to your Member of Parliament and let them know how you feel about the blocking of the Scottish Gender Recognition Bill. Your words carry weight, and speaking up is a way to defend the rights of the LGBTQ+ community. So let's do our part and make sure our opinions are heard loud and clear."

export const emailContent = {
  address: 'michelle.donelan.mp@parliament.uk',
  subject: 'Expressing Concern about the Rejection of Scottish Gender Recognition Bill',
  body: "Dear  Michelle Donelan %0A%0AI am writing to you today as a concerned citizen and an advocate for the rights of the LGBTQ  community. I am deeply worried about the potential rejection of the Scottish gender recognition bill, which was passed with overwhelming cross-party support in December 2022. %0A%0AThis bill aimed to implement a self-identification system for transgender individuals, providing them with the dignity and respect they deserve. As a member of Parliament, you have a responsibility to represent the views of your constituents and I strongly believe that it is crucial for you to support this bill. %0A%0AI understand that there are different opinions on this matter, but I believe that the rights of trans individuals should not be put at risk. Rejecting the Scottish gender recognition bill would not only be a setback for the LGBTQ  community, but it would also send a message that the UK government sees trans people as a threat to be contained, not citizens to be respected. %0A%0AI urge you to consider the impact of your actions on the trans community and to take a stand for equality and respect for all. I would be happy to discuss this matter with you further and answer any questions you may have. %0A%0AThank you for taking the time to read my letter. I look forward to your response. %0A%0ASincerely, %0A%0A\[Your Name\] %0A%0A\[Your Address\]"
}