export const eventDetails = [
  {
    data: [
      {
        name: "Stuart Rolfe",
        url: 'https://www.facebook.com/DaylightStealers/?locale=en_GB',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Sam",
        url: 'https://www.instagram.com/samistackers/',
        img: "https://i.postimg.cc/9FdLBT9H/sam.png",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Becky Lawrence",
        url: 'https://beckylawrence.co.uk/',
        img: "https://i.postimg.cc/BbZqpByt/becky-Lawrence.png",
        type: "singer",
        description: "Drifted from the shores of the Isle of Man, Becky Lawrence is a singer/songwriter and storyteller, now residing in Wiltshire. From years of threading the boards in hit shows such as 'Les Miserables', 'Miss Saigon' and 'Evita', to cowboy boots and writing her own songs, Becky loves nothing more then bringing her audience on a journey everytime she performs. She'll make you laugh, sometimes make you cry and above all, she hopes she can make you feel or heal through her story telling.",
      },
      {
        name: "The Real Cheesemakers",
        url: 'https://realcheesemakers.com/',
        img: "https://i.postimg.cc/0NXv2h5n/trc.jpg",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Boston Green",
        url: 'https://www.facebook.com/BOSTONGREEN123456/',
        img: "https://i.postimg.cc/qMJJkc41/bgreen.jpg",
        type: "singer",
        description: "They’ve written multiple originals with varying influences between each of the songs. They sit within an Indie-Rock/Alternative genre, but be prepared to hear many of your favourite songs from throughout the years as they love taking covers and bringing a new spin on them.",
      },
      {
        name: "Concrete Prairie",
        url: 'https://google.com',
        img: "https://i.postimg.cc/050hnLDN/concerte-praire.jpg",
        type: "singer",
        description: "United by a love of all things Indie, Folk & Americana, Concrete Prairie are a five-piece ensemble delivering a veritable soundtrack for the glamour and grit of modern living. While their compositions tackle themes such as mental well-being, loss and hardships, the songs are shot through with hope, evidenced by a spirited and rousing sound orchestrated with twanging guitars, straining fiddle and yearning prose. Dance if you dare, cry if you want to.",
      },
      {
        name: "Rock Choir North Wiltshire",
        url: 'https://www.facebook.com/rockchoirnorthwiltshire',
        img: "https://i.postimg.cc/kDrkzmJ1/rock-choir.jpg",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/main-stage",
    type: "main stage",
  },
  {
    data: [
      {
        name: "Stuart Rolfe",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/small-stage",
    type: "small stage",
  },
  {
    data: [
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/speakers",
    type: "speakers theatre",
  },
  {
    data: [
      {
        name: "Andrew O'Neil",
        url: 'https://www.andrewoneill.co.uk/',
        img: "https://www.chortle.co.uk/images/photos/small/aon-andrew-oneill-22.jpg",
        type: "comedian",
        description: "Andrew O'Neill is an award-winning comedian,  musician and best-selling writer. A psychedelic non-binary whirlwind, they combine surrealism, polemic and good old-fashioned stagecraft to produce uniquely counter-cultural stand-up.",
      },
      {
        name: "Sooz Kempner",
        url: 'https://www.soozkempner.co.uk/',
        img: "https://cdn.comedy.co.uk/images/library/people/900x450/s/sooz_kempner.jpg",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
      {
        name: "Jonathan Mayor",
        url: 'https://google.com',
        img: "https://www.comedygigs.co.uk/img-artists/artist-1183-1.jpg",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/comedy",
    type: "comedy",
  },
  {
    data: [
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/community-stalls",
    type: "stalls",
  },
  {
    data: [
      {
        name: "Stu",
        url: 'https://google.com',
        img: "https://i.scdn.co/image/ab6761610000e5eb2f34440ca30dd0c4e8f6b588",
        type: "singer",
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
      },
    ],
    url: "/details/commercial-stalls",
    type: "stalls",
  },
];
